clang-tidy: fix strict-prototypes in init
Declare and define the constructor as init(void) instead of init().
This resolves -Wstrict-prototypes under Clang (and with -Werror) and
uses the correct modern C form for a no-argument function.

Fixed below errors
'''
../peci.c:65:17: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
   65 | static void init() __attribute__((constructor));
      |                 ^
      |                  void
../peci.c:66:17: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
   66 | static void init()
      |                 ^
      |                  void
'''

Change-Id: I0bcb426d53bb98f70808cec8efb719017616e94e
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>